export const enum GridEntityType {
    NULL = 0,
    DECORATION = 1,
    ROCK,
    ROCKB,
    TINTED_ROCK,
    BOMB_ROCK,
    POT,
    MUSHROOM,
    SKULL,
    PIT,
    SPIKES,
    SPIKES_ONOFF,
    SPIDERWEB,
    LOCK,
    TNT,
    FIREPLACE,
    POOP,
    WALL,
    DOOR,
    TRAPDOOR,
    STAIRS,
    GRAVITY,
    PRESSURE_PLATE,
    STATUE,
    SUPER_TINTED_ROCK,
    TELEPORTER,
    PILLAR,
    SPIKED_ROCK,
    TINTED_SKULL,
    GOLD_ROCK
}